### PR TITLE
Make it possible to set entrypoint for working_container.

### LINKED ISSUE #198: Ability to set entrypoint on working container
Currently, only target_image context supports the setup of the entrypoint, which is affects only "production" image.

In cases, where base image already has an entrypoint, ansible-bender will stuck during the build, due endless process running by container.

This problem can be solved by adding the ability to setup entrypoint for working container , this entrypoint will override the entrypoint of the base image:
```
 vars:
    ansible_bender:
      working_container:
        entrypoint: <an_entrypoint>
```

### PR DESCRIPTION
**Pull request by Smeds**
Fixes #198

### CODE REVIEW

**Review by TomasTomecek — COMMENTED** [review]
Nice, looking good!

Would you be interested in adding the parameter to [documentation](https://github.com/ansible-community/ansible-bender/blob/master/docs/configuration.md) and writing a test case? If not, I can do that myself.

**Comment by Smeds** [comment]
Absolutely! I will put same time on documentation and testing later this week.

**Comment by Smeds** [comment]
Added some content and a simple test! But I must say that I don't really know every place where I should add entries for testing.

**Comment by TomasTomecek** [comment]
Thanks, looking good! This is fine for me. I'm gonna play with it a bit more tomorrow.

**Comment by TomasTomecek** [comment]
I played with it locally a bit and found two issues which I fixed and pushed a commit to your branch.

Can someone verify this works correctly? I looked into entrypoint details and the thing is that buildah doesn't seem to use that value for a working container:
```
$ man buildah-config
...
       --entrypoint "command" | '["command", "arg1", ...]'

       Set  the  entry point for containers based on any images which will be built using the specified container. buildah supports two formats for entrypoint.  It can be specified as a
       simple string, or as a array of commands.

       Note: When the entrypoint is specified as a string, container runtimes will ignore the cmd value of the container image.  However if you use the array form, then the cmd will  be
       appended onto the end of the entrypoint cmd and be executed together.
```

Or maybe I don't understand the manpage.

**Comment by TomasTomecek** [comment]
test failures are unrelated, merging

thank you for your contribution!

**Review by TomasTomecek — APPROVED** [review]

**Pull request merged**
