### PR TITLE
Better errors for json validation in ab

### LINKED ISSUE #102: better error messages when var -> ansible_bender is not set
```
$ ansible-bender build -- ./recipe-tests.yaml  packit-tests
There was an error during execution: None is not of type 'string'

Failed validating 'type' in schema['properties']['target_image']:
    {'$id': '#/properties/target_image',
     'examples': ['my-funky-image'],
     'pattern': '^(.*)$',
     'title': 'Name of the final image which we build',
     'type': 'string'}

On instance['target_image']:
    None
```

The error should say that base_image or target_image is required. Probably just update title in the schema.

### LINKED ISSUE #187: Improve error message when base_image or target_image are not set
When you invoke bender like this:
```
$ ansible-bender build playbook.yaml
```
and the base_image or target_image are not set, you get an error message coming from this traceback:
```
None is not of type 'string' in target_image property
Traceback (most recent call last):
  File "/home/tt/.local/bin//ansible-bender", line 11, in <module>
    load_entry_point('ansible-bender', 'console_scripts', 'ansible-bender')()
  File "/home/tt/g/ab/ansible_bender/cli.py", line 395, in main
    sys.exit(CLI().run())
  File "/home/tt/g/ab/ansible_bender/cli.py", line 362, in run
    self._build()
  File "/home/tt/g/ab/ansible_bender/cli.py", line 309, in _build
    self.app.build(build)
  File "/home/tt/g/ab/ansible_bender/api.py", line 66, in build
    self.db.record_build(build)
  File "/home/tt/g/ab/ansible_bender/db.py", line 185, in record_build
    build_i.build_container = generate_working_cont_name(build_i.target_image)
  File "/home/tt/g/ab/ansible_bender/db.py", line 66, in generate_working_cont_name
    san = image_name.replace(".", "-").replace(":", "-").replace("/", "-")
AttributeError: 'NoneType' object has no attribute 'replace'
```
Let's get more sensible error message.

### PR DESCRIPTION
**Pull request by kmehant**
fixes #187

### CODE REVIEW

**Comment by kmehant** [comment]
@TomasTomecek Please review!

**Comment by kmehant** [comment]
> I don't understand how does this PR solve the issue. You catch the exception, print an error message and don't raise anything, which means the flow continues as if no exception has happened.
> 
> The issue is about a situation, when the configuration is valid, but there is a key which is not listed in the schema: maybe jsonschema is able to accept only a list of keys - this would be ideal. Otherwise we need to check for this the way you proposed: compare the sets of expected keys and actual keys and if the actual keys are not a subset, raise an exception.
> 
> Does this make more sense?

@TomasTomecek My aim was to manipulate the actual error messages from jsonschema to make it more understandable, ab centric rather jsonschema validation centric for a user (for which I used the member variables to construct better messages). Perhaps I should do something to terminate the process after the error manipulation (may be I should `raise` a final exception after my error message manipulation). This is something I tried solving and something I misunderstood from the https://github.com/ansible-community/ansible-bender/issues/102

**Comment by TomasTomecek** [comment]
Could you please show me an example how the error message is better - I tried a few runs but couldn't make it print the right thing. I feel like you are trying to solve a different problem than the referenced issue (which is perfectly fine!), I just want to understand the use case in detail, thank you!

My original issue is about a scenario like this: I may have a playbook like this:
```
---         
- name: Containerized ansible-bender
  hosts: all                          
  vars:                                                                                                                                                                                                            
    test_mode: no  # yes - test in CI, no - build an image
    project_dir: /src
    with_tests: no  # yes - run test suite
    with_bender_install: yes
    ansible_bender:
      case_image: asdqwe
      target_image:
        workging_dir: /src
        cmd: /entry.sh
        name: bender
      working_container:
        volumes:
        - "{{ playbook_dir }}:/src"
```
You can see there is a key `case_image` when it should be a `base_image`. In such a case, I'd expect bender to tell me that `case_image` is an invalid value - does that make sense? Right now, bender would not care about keys which it does not parse.

**Comment by kmehant** [comment]
> Could you please show me an example how the error message is better - I tried a few runs but couldn't make it print the right thing. I feel like you are trying to solve a different problem than the referenced issue (which is perfectly fine!), I just want to understand the use case in detail, thank you!
> 
> My original issue is about a scenario like this: I may have a playbook like this:
> 
> ```
> ---         
> - name: Containerized ansible-bender
>   hosts: all                          
>   vars:                                                                                                                                                                                                            
>     test_mode: no  # yes - test in CI, no - build an image
>     project_dir: /src
>     with_tests: no  # yes - run test suite
>     with_bender_install: yes
>     ansible_bender:
>       case_image: asdqwe
>       target_image:
>         workging_dir: /src
>         cmd: /entry.sh
>         name: bender
>       working_container:
>         volumes:
>         - "{{ playbook_dir }}:/src"
> ```
> 
> You can see there is a key `case_image` when it should be a `base_image`. In such a case, I'd expect bender to tell me that `case_image` is an invalid value - does that make sense? Right now, bender would not care about keys which it does not parse.

@TomasTomecek I got it, I would like to work on that in a separate PR.

**Comment by kmehant** [comment]
@TomasTomecek I made new changes and now this PR aligns to #187. I wish to have your review if this approach is fine to solve the issue #187

**Comment by kmehant** [comment]
@TomasTomecek not sure why packit taking forever to start tests, its been about  13 hours but there is no change yet.

**Comment by TomasTomecek** [comment]
> @TomasTomecek not sure why packit taking forever to start tests, its been about 13 hours but there is no change yet.

Yeah, I saw that, seems like there was some infrastructure problem.

**Comment by TomasTomecek** [comment]
I was finally able to reproduce:
```
There was an error during execution: {} is not of type 'string', 'null' in target_image property. 
```
```
There was an error during execution: '' is not of type 'array' in working_container property. 
```

Sadly it didn't tell me which exact property I misconfigured. In this case, I changed working_dir and volumes.

**Comment by kmehant** [comment]
> I was finally able to reproduce:
> 
> ```
> There was an error during execution: {} is not of type 'string', 'null' in target_image property. 
> ```
> 
> ```
> There was an error during execution: '' is not of type 'array' in working_container property. 
> ```
> 
> Sadly it didn't tell me which exact property I misconfigured. In this case, I changed working_dir and volumes.

@TomasTomecek sorry, I haven't checked this case, anyways I made some changes for this to work at all levels, please review!

**Pull request merged**
