### PR TITLE
don't tag layers with names by default

### LINKED ISSUE #59: don't tag intermediate layers with a name
It clutters the output of `buildah images` a lot.

Edit: since this is already done, let's make it configurable and default to not use a name

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #59

TODO:

* [x] ~~blocked on lack of support in buildah~~
* [x] write image id to a file using `--iidfile string                Write the image ID to the file`
* [x] use `-q`

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Sadly, buildah does not allows this: image name argument of commit command is required:
```
$ buildah commit prgcont
an image name must be specified
ERRO[0000] exit status 1          
```

**Comment by jamescassell** [comment]
Seems like a bug in buildah.

**Comment by TomasTomecek** [comment]
@jamescassell yup!

But it works now with buildah 1.8
```
$ buildah from python:3-alpine
python-working-container

$ buildah commit python-working-container
Getting image source signatures
Copying blob 767f936afb51 skipped: already exists
Copying blob b211a7fc6e85 skipped: already exists
Copying blob 8d092d3e44bb skipped: already exists
Copying blob 492c5c55da84 skipped: already exists
Copying blob 6f55b6e55d8a skipped: already exists
Copying blob 5f70bf18a086 skipped: already exists
Copying config d11913f691 done
Writing manifest to image destination
Storing signatures
d11913f6916d266a7b85cbeda28fc2305e5188bcf0a653d9af41221b18e427b4
```

**Comment by TomasTomecek** [comment]
will merge & release soon

**Pull request merged**
