### PR TITLE
workaround ansible bug with selinux on and...

### LINKED ISSUE #101: ansible-bender build hangs
```
$ git clone https://github.com/packit-service/packit.git
$ ansible-bender build -- ./recipe.yaml
```

It hangs indefinitely. With `--debug` I can see
```
utils.py DEBUG  TASK [copy]  ****
utils.py DEBUG  fatal: [localhost]: FAILED! => {"changed": false, "checksum": "71dfb412ae517d2a4442e26331f29f5d9ecc7dd1", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```

### PR DESCRIPTION
**Pull request by TomasTomecek**
no python bindings for selinux installed

Fixes #101

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Ehm, some tests are failing with
```
TASK [print local env vars] ****************************************************
16:28:34.271 utils.py          ERROR  Error: could not get runtime: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containe
rs/storage/libpod: permission denied
ok: [registry-example-com-ab-test-dhhjclwbllrb-oldest-20190405-162828211628-cont] => {
    "msg": "/tmp/abse5r_00d/ansible.cfg,,"
}
```

using rootless buildah

**Comment by TomasTomecek** [comment]
I will cut a new release after this one is merged.

**Comment by jpopelka** [comment]
Yes, that makes bender to exit right away.

**Comment by TomasTomecek** [comment]
Tomas' wonderful CI status: passed
```
=== 60 passed in 843.71 seconds ===
```

**Pull request merged**
