### PR TITLE
add GHA: build and publish releases to PyPI

### PR DESCRIPTION
**Pull request by TomasTomecek**
...using the Trusted Publisher Management:

- https://docs.pypi.org/trusted-publishers/
- https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
- https://github.com/pypa/gh-action-pypi-publish#trusted-publishing

Fixes: https://github.com/ansible-community/ansible-bender/issues/291

### CODE REVIEW

**Comment by TomasTomecek** [comment]
@webknjaz this should work, I followed the docs and a bunch of examples

sadly I didn't find an example where build and publish are separate jobs, everyone does it as one

**Comment by webknjaz** [comment]
> sadly I didn't find an example where build and publish are separate jobs, everyone does it as one

None of my project has these in the same job. Let me find an example..

**Comment by webknjaz** [comment]
Basically, you need to use download and upload actions for this https://github.com/cherrypy/cheroot/blob/56d7b49/.github/workflows/ci-cd.yml#L989

**Comment by TomasTomecek** [comment]
> Basically, you need to use download and upload actions for this https://github.com/cherrypy/cheroot/blob/56d7b49/.github/workflows/ci-cd.yml#L989

Thank you. I'll add it as TODO and will start with the current implementation.

**Pull request merged**
